import { poppins } from "@/lib/fonts";
import "./globals.css";

export const metadata = {
  title: "Gaia Learning",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.variable}`}>
      <body className="regular">{children}</body>
    </html>
  );
}
